services:
  app:
    build:
      target: dev
    command: air
    environment:
      GIN_MODE: "debug"
    ports:
      - "5864:5864"

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"