{
 "title": "Notification RPC",
 "tags": [
  "notification",
  "rpc",
  "influxdb",
  "telegraf",
  "pet-project"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total sent (success)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_stats\" and r._field == \"total\" and r.type == \"success\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()\n  |> group(columns: [\"_time\"])           // суммируем все instance\n  |> sum(column: \"_value\")\n  |> aggregateWindow(every: inf, fn: last) // одна точка для stat"
    }
   ]
  },
  {
   "title": "Total failed (error)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_stats\" and r._field == \"total\" and r.type == \"error\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()\n  |> group(columns: [\"_time\"])           // суммируем все instance\n  |> sum(column: \"_value\")\n  |> aggregateWindow(every: inf, fn: last) // одна точка для stat"
    }
   ]
  },
  {
   "title": "Sent by channel (type=success, stacked)",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_stats\" and r._field == \"total\" and r.type == \"success\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()\n  |> group(columns: [\"channel\",\"_time\"]) // суммируем все instance в рамках времени и канала\n  |> sum(column: \"_value\")\n  |> group(columns: [\"channel\"])          // серии по channel (stack)"
    }
   ]
  },
  {
   "title": "Failed by channel (type=error, stacked)",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_stats\" and r._field == \"total\" and r.type == \"error\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()\n  |> group(columns: [\"channel\",\"_time\"]) // суммируем все instance в рамках времени и канала\n  |> sum(column: \"_value\")\n  |> group(columns: [\"channel\"])          // серии по channel (stack)"
    }
   ]
  },
  {
   "title": "RPS (1s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"counter\")\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\n  |> yield(name: \"rps\")"
    }
   ]
  },
  {
   "title": "RPM (1m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"counter\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\n  |> yield(name: \"rpm\")"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 28, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"duration_ms\")\r\n  |> window(every: 1m)\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> window(every: inf)\r\n  |> keep(columns: [\"_time\",\"_value\"])"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 28, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"duration_ms\")\r\n  |> window(every: 1m)\r\n  |> quantile(q: 0.99, method: \"estimate_tdigest\")\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> window(every: inf)\r\n  |> keep(columns: [\"_time\",\"_value\"])"
    }
   ]
  },
  {
   "title": "Bytes written per minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"bytes_written\")\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> yield(name: \"bytes_per_min\")"
    }
   ]
  },
  {
   "title": "In-flight requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 36, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"notification_rpc\" and r._field == \"inflight\")\n  |> aggregateWindow(every: 10s, fn: mean)\n  |> yield(name: \"inflight\")"
    }
   ]
  }
 ]
}